customCommands:
  - key: "<c-c>"
    description: "Conventional Commit"
    context: "files"
    prompts:
      - type: "menu"
        title: "What kind of commit is it?"
        key: "CommitType"
        options:
          - name: "âœ¨feature"
            description: "a new feature"
            value: "feat"
          - name: "ğŸ›fix"
            description: "fix a bug"
            value: "fix"
          - name: "ğŸ”¨refactor"
            description: "refactor code"
            value: "refactor"
          - name: "ğŸ“šdocumentation"
            description: "change documentation"
            value: "docs"
          - name: "ğŸš¨test"
            description: "work on tests"
            value: "test"
          - name: "ğŸš€performance"
            description: "improve performance"
            value: "perf"
          - name: "ğŸ‘”style"
            description: "improve style/format"
            value: "style"
          - name: "ğŸ§¹chore"
            description: "change auxiliary tools"
            value: "chore"
          - name: "ğŸ¤–CICD"
            description: "change cicd pipeline"
            value: "ci"
          - name: "ğŸš§build"
            description: "change build system"
            value: "build"
          - name: "ğŸ”™revert"
            description: "revert to a previous commit"
            value: "revert"
      - type: "input"
        title: "What is the scope of this commit (optional)?"
        key: "Scope"
        initialValue: ""
      - type: "input"
        title: "Breaking change - Add '!'"
        key: "Breaking"
        initialValue: ""
      - type: "input"
        title: "What is your commit message?"
        key: "CommitMessage"
        initialValue: ""
      - type: "input"
        title: "What is your commit description (optional)?"
        key: "CommitDescription"
        initialValue: ""
      - type: "input"
        title: "Footer for referencing (optional)"
        key: Footer
        initialValue: ""
    command: 'git commit -m ''{{.Form.CommitType}}{{if .Form.Scope}}({{.Form.Scope}}){{end}}{{.Form.Breaking}}: {{.Form.CommitMessage}}'' -m "$(echo ''{{.Form.CommitDescription}}'' | fmt -w 72)" -m ''{{.Form.Footer}}'''
    loadingText: "Committing changes"
  - key: "<c-T>"
    description: "Commitizen bump"
    command: "cz bump && git push && git push --tags"
    context: "global"
    loadingText: "bumping to the next version"
